### ISSUE TITLE
ClientSocket: Failed to connnet Socket: Error in select<>. 

### ISSUE THREAD

**Issue by Macleowh** [khanh245/Windows-Socket#1]
why i use your code in VS2013 Win 7 Environment, When i compiler the project, I have those responding:
Attempting to connect...
ClientSocket: Connetting to 127.0.0.1：2605
ClientSocket: Failed to connnet
Connected...
Socket: Error in select<>.
Socket: Error sending data <>.
Socket: Error in select<>.
Socket: Error sending data <>.
ServerSocket：Listening for client ...
ServerSocket：Accepting connetion...

**Comment by khanh245** [comment]
Hello, 

I was able to simulate the program. Make sure you've disabled/opened your firewall settings. 

ServerSocket:
![ServerSocket](https://user-images.githubusercontent.com/5744118/29105195-10c50972-7c80-11e7-8a7e-7182fcf8679f.png)

ClientSocket:
![ClientSocket](https://user-images.githubusercontent.com/5744118/29105204-22e67c62-7c80-11e7-8f26-cb90267c7422.png)


Thanks,

**Comment by Macleowh** [comment]
thank you for your help，it works well！That is great！




发自网易邮箱大师
On 08/09/2017 12:26, Khanh Nguyen wrote:

Closed #1.
